# ${DOCKER_GROUP} and ${DOCKER_TAG} default values defined in the .env file 
version: '3'
services:
    sounder_sips_dev:
        image: ${DOCKER_GROUP}/sounder_sips_dev:${DOCKER_TAG}
        hostname: local
        build:
            context: sounder_sips_dev/
            dockerfile: $PWD/sounder_sips_dev/Dockerfile
    unity_datascience:
        image: ${DOCKER_GROUP}/datascience:${DOCKER_TAG}
        hostname: local
        build:
            context: unity_datascience
            dockerfile: $PWD/unity_datascience/Dockerfile
